### ISSUE TITLE
Error running tool

### ISSUE THREAD

**Issue by ManuelBot59** [osintmatter/shortemall#1]
selenium.common.exceptions.WebDriverException: Message: 'shortemall' executable may have wrong permissions. 

Taking awesome screenshots for you ...                                                                                                      
Traceback (most recent call last):

![screen 2022-06-17 152333](https://user-images.githubusercontent.com/89365972/174396404-3640a326-f430-4f8b-a8e3-f4456738f1d0.png)

**Comment by osintmatter** [comment]
Chromium isn't available anymore as an apt installation in Ubuntu, but uses snap. It remaps the /tmp folder. Info in the first long answer here: https://pythonfixing.com/2021/10/fixed-webdriverexception-unknown-error.html

I suggest to manually change the Python script to include "--user-data-dir=/home/{install path}" as an argument, and it's should solve the issue. Another option is to use the Chromium version of the chromedriver.
